version: "2.0"

dependencies: ./dependencies.yaml
default: 
  build-command:
    upstream: echo 'build-command --> upstream!'
    current: echo 'build-command --> current!'
    downstream: echo 'build-command --> downstream!'
    after:
      upstream: echo 'AFTER>>!'
build: 
  - project:bacciotti/build-chain-test-1
    build-command:
      upstream: echo 'build-command --> upstream---->!'
      current: echo 'build-command --> current---->!'